### ISSUE TITLE
Can't run Lesson 1

### ISSUE THREAD

**Issue by qzhang234** [BCDA-APS/use_bluesky#102]
This is a dumb question, but I started the binder session to run lesson 1 and I got an error saying that `Ophyd` is not imported, which just by looking at the Jupyter Notebook file that does seem to be the case. 

Any suggestions @prjemian?

<img width="1211" alt="Screen Shot 2021-04-07 at 3 41 18 PM" src="https://user-images.githubusercontent.com/48140482/113931125-b962c780-97b7-11eb-87f7-b029398982e4.png">
<img width="1273" alt="Screen Shot 2021-04-07 at 3 40 45 PM" src="https://user-images.githubusercontent.com/48140482/113931050-a819bb00-97b7-11eb-8d97-9b46c20524ab.png">

**Comment by prjemian** [comment]
You won't be able to run this from Binder, at least not yet.  Even if that import were to work, you would not have any EPICS PVs available in the Binder session.  I'm working on solving that problem differently so this won't get worked on now.
