### ISSUE TITLE
test mac_2022_1.yml conda environment

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#112]
This file was copied directly from its Windows counterpart.  Needs testing on a Mac.

**Comment by prjemian** [comment]
@rodolakis, @jsullivan-anl - Are either of you able to test if this conda environment works on a Mac?

1. download this text file to local file `mac_2022_1.yml`: https://raw.githubusercontent.com/BCDA-APS/use_bluesky/main/install/mac_2022_1.yml
2. in terminal/console/whatever, with conda base environment activated: `conda env create --force -f mac_2022_1.yml`

Should result in a new conda environment installed with name `bluesky_2022_1`

**Comment by rodolakis** [comment]
It appears to be working:


# To activate this environment, use
#
#     $ conda activate bluesky_2022_1
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) iMac:macros_29id fannysimoes$ conda activate bluesky_2022_1
(bluesky_2022_1) iMac:macros_29id fannysimoes$ ipython
Python 3.9.7 (default, Sep 16 2021, 08:50:36)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import apstools; print(apstools.__version__)
1.5.3



Fanny Rodolakis | 29-ID IEX Beamline Scientist

a.k.a. Fanny Simoes

Advanced Photon Source | Argonne National Laboratory
9700 S Cass Avenue, Bldg. 437-D004, Argonne IL 60439
Office: (630) 252-6817 | Beamline: (630) 252-2601
Email: ***@***.******@***.***> | 29-ID Website<https://www.aps.anl.gov/Sector-29/29-ID>

________________________________

**Comment by prjemian** [comment]
@rodolakis @gfabbris : Thanks for the testing.
