### ISSUE TITLE
get complete image frame file name into event document

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#12]
In #6, the parts of the file name are in the event document but the full name is not.  That is provided from EPICS as a waveform string and ophyd does not render that in the event document.  Yet.

**Comment by tacaswell** [comment]
I think you can get this via

```python
ad_obj.read_attrs = ['hdf5.filename']
```

where 'filename' is the signal that has the filname in it and 'hd5' is the name of your file plugin.
