### ISSUE TITLE
Warnings thrown during use_bluesky/IPython exit

### ISSUE THREAD

**Issue by mdwyman** [BCDA-APS/use_bluesky#24]
@tcaswell, @danielballan

When exiting IPython (simply using "exit") after a Bluesky session (which was started with use_bluesky.sh), many copies of the following warning are shown: 

Traceback (most recent call last):
  File "/home/mwyman/Apps/BlueSky/lib/python3.6/site-packages/epics/ca.py", line 251, in initialize_libca
  File "/home/mwyman/Apps/BlueSky/lib/python3.6/site-packages/epics/ca.py", line 213, in find_libCom
  File "/home/mwyman/Apps/BlueSky/lib/python3.6/site-packages/epics/ca.py", line 178, in _find_lib
  File "/home/mwyman/Apps/BlueSky/lib/python3.6/ctypes/util.py", line 302, in find_library
  File "/home/mwyman/Apps/BlueSky/lib/python3.6/ctypes/util.py", line 249, in _findSoname_ldconfig
ImportError: sys.meta_path is None, Python is likely shutting down

Is this related to MonitorDispatcher thread running (but not stopped) at exit? Is there a cleaner way to exit?

Thanks,
Max

**Comment by danielballan** [comment]
That is the standard way to exit and, if everything goes as planned, IPython should exit cleanly without a traceback like this. Is [this function](https://github.com/NSLS-II/ophyd/blob/master/ophyd/utils/startup.py#L15) run as part of your IPython profile? I might need more context from @prjemian to know what to look for here.

P.S. You're looking for @tacaswell -- missing the A.

**Comment by tacaswell** [comment]
This may also be a pyepics bug, see https://github.com/pyepics/pyepics/issues/89 and https://github.com/pyepics/pyepics/pull/102

Should be fixed in the latest version of pyepics.

**Comment by prjemian** [comment]
We *do* [run the `setup()` function](https://github.com/BCDA-APS/use_bluesky/blob/master/setup/ipython_startups/mongodb/00-startup.py#L5).  I've seen this on a couple computers.  Up to now, been ignoring it as "exit comments".  There _may_ be a way to quiet them.  I'll check those two PyEpics issues and our version number.

**Comment by prjemian** [comment]
not seeing this, closing (open new if seen again)
