### ISSUE TITLE
prepare for tomo instrument

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#4]
We are ready to try Blue Sky on a tomography instrument.

* Q:   Are there plans for tomo collection?  
* Q:  Or a suggestion where to find a starting template?

**Comment by prjemian** [comment]
Dan Allan replies:

Great! We have a good template for you.


https://github.com/danielballan/docs/blob/0f3e97892db11c59c029204e69a5d6d455331961/source/_cookbook/live_recon.py

This is a PR into our documentation cookbook. The only reason it isn't published yet is that we need get all the dependencies right on Travis-CI. It works locally: see attached GIF.

**Comment by prjemian** [comment]
Dan:

That's a start.  Thanks.  Your example is informative for several aspects (custom callbacks, instantiation and use of several callbacks as subs to RE(), clear syntax when calling RE(), simple use of scan() in this context).

We plan to expand on the "scan" plan to include a multi-dimensional algorithm that takes an inside scan of coarse angular steps, and an outer scan that offsets the starting angle.  Results in the high-density angle map normally taken but collections builds up the sinogram from lower-density (inner loop) fragments.  We'll couple that to tomopy running on a remote client.

Pete

**Comment by prjemian** [comment]
Dan writes:

Great. You [may] already be aware, but it sounds like these sections of the documentation might be useful:

- Combining "inner product" and "outer product" scans: http://nsls-ii.github.io/bluesky/plans.html#multi-dimensional-scans (see bottom of that subsection, the stuff using 'cycler')
- Binding subscriptions to a plan (so you don't have to pass them to RE every time...) http://nsls-ii.github.io/bluesky/callbacks.html#through-a-plan

**Comment by prjemian** [comment]
This initial test code might need to work standalone rather than interactive.  Barbara's framework expects to call this code *from* the framework rather than react to this code operating asynchronously.  We can do that, I believe.

**Comment by prjemian** [comment]
on 2017-03-23, Doga emailed:

I put the current [tomography] scan scripts at the project repo: https://github.com/dgursoy/mona/blob/master/trunk/32id/tomo_step_scan.py

**Comment by prjemian** [comment]
BTW, the work here should migrate to mona, once it moves out of initial development.

**Comment by prjemian** [comment]
demo needs an area detector to be realistic, use the [ADSimDetector](https://github.com/areaDetector/ADSimDetector)

**Comment by prjemian** [comment]
Regarding 460820a, for these commands

    import interlace_tomo
    
    callbacks = []
    detectors = [scaler,]
    lt = LiveTable([scaler.time, scaler.channels.chan1, scaler.channels.chan2, alpha, beta])
    enc = interlace_tomo.EPICSNotifierCallback("xxx:userStringCalc1.AA", "xxx:userStringCalc1.BB")
    callbacks.append(lt)
    callbacks.append(enc)
    
    #plan = interlace_tomo.tomo_scan(detectors, alpha, 1.0, 2.0, 5)
    #RE(plan, callbacks, md=dict(developer=True))
    
    plan = interlace_tomo.interlace_tomo_scan(detectors, alpha, 1, 2, 5, 5, snake=True)
    RE(plan, callbacks, md=dict(developer=True))
    
    plan = interlace_tomo.interlace_tomo_scan(detectors, alpha, 0.8, 0.0, 5, 4)
    RE(plan, callbacks, md=dict(developer=True))

This was the output with `snake=True`

	Loading metadata history from /home/prjemian/.config/bluesky/bluesky_history.db
	Transient Scan ID: 76
	Persistent Unique Scan ID: 'c92dfbea-cf0b-4d9c-8484-798d47e631ea'
	+-----------+------------+-------------+-----------------------+-----------------------+------------+---------------------+
	|   seq_num |       time | scaler_time | scaler_channels_chan1 | scaler_channels_chan2 |      alpha | alpha_user_setpoint |
	+-----------+------------+-------------+-----------------------+-----------------------+------------+---------------------+
	|         1 | 17:45:27.6 |       1.000 |              10000000 |                     5 |    1.00000 |             1.00000 |
	|         2 | 17:45:29.3 |       1.000 |              10000000 |                     3 |    1.25000 |             1.25000 |
	|         3 | 17:45:30.9 |       1.000 |              10000000 |                     5 |    1.50000 |             1.50000 |
	|         4 | 17:45:32.5 |       1.000 |              10000000 |                     6 |    1.75000 |             1.75000 |
	|         5 | 17:45:34.0 |       1.000 |              10000000 |                     2 |    2.00000 |             2.00000 |
	|         6 | 17:45:35.7 |       1.000 |              10000000 |                     3 |    1.80000 |             1.80000 |
	|         7 | 17:45:37.3 |       1.000 |              10000000 |                     5 |    1.55000 |             1.55000 |
	|         8 | 17:45:38.9 |       1.000 |              10000000 |                     5 |    1.30000 |             1.30000 |
	|         9 | 17:45:40.5 |       1.000 |              10000000 |                     6 |    1.05000 |             1.05000 |
	|        10 | 17:45:41.9 |       1.000 |              10000000 |                     4 |    1.10000 |             1.10000 |
	|        11 | 17:45:43.5 |       1.000 |              10000000 |                     5 |    1.35000 |             1.35000 |
	|        12 | 17:45:45.1 |       1.000 |              10000000 |                     4 |    1.60000 |             1.60000 |
	|        13 | 17:45:46.7 |       1.000 |              10000000 |                     4 |    1.85000 |             1.85000 |
	|        14 | 17:45:48.1 |       1.000 |              10000000 |                     6 |    1.90000 |             1.90000 |
	|        15 | 17:45:49.7 |       1.000 |              10000000 |                     6 |    1.65000 |             1.65000 |
	|        16 | 17:45:51.2 |       1.000 |              10000000 |                     6 |    1.40000 |             1.40000 |
	|        17 | 17:45:52.8 |       1.000 |              10000000 |                     5 |    1.15000 |             1.15000 |
	|        18 | 17:45:54.4 |       1.000 |              10000000 |                     4 |    1.20000 |             1.20000 |
	|        19 | 17:45:56.1 |       1.000 |              10000000 |                     5 |    1.45000 |             1.45000 |
	|        20 | 17:45:57.8 |       1.000 |              10000000 |                     3 |    1.70000 |             1.70000 |
	|        21 | 17:45:59.4 |       1.000 |              10000000 |                     4 |    1.95000 |             1.95000 |
	+-----------+------------+-------------+-----------------------+-----------------------+------------+---------------------+
	generator interlace_tomo_scan ['c92dfb'] (scan num: 76)
	wrote: /home/prjemian/Documents/eclipse/use_bluesky/plans/developer_76.h5

Then with `snake=False`:

	Transient Scan ID: 77
	Persistent Unique Scan ID: '23914c88-d4a5-4d60-85d5-471213fdd509'
	+-----------+------------+-------------+-----------------------+-----------------------+------------+---------------------+
	|   seq_num |       time | scaler_time | scaler_channels_chan1 | scaler_channels_chan2 |      alpha | alpha_user_setpoint |
	+-----------+------------+-------------+-----------------------+-----------------------+------------+---------------------+
	|         1 | 17:46:02.5 |       1.000 |              10000000 |                     6 |    0.80000 |             0.80000 |
	|         2 | 17:46:04.2 |       1.000 |              10000000 |                     4 |    0.60000 |             0.60000 |
	|         3 | 17:46:05.9 |       1.000 |              10000000 |                     4 |    0.40000 |             0.40000 |
	|         4 | 17:46:07.6 |       1.000 |              10000000 |                     5 |    0.20000 |             0.20000 |
	|         5 | 17:46:09.2 |       1.000 |              10000000 |                     6 |    0.00000 |             0.00000 |
	|         6 | 17:46:11.4 |       1.000 |              10000000 |                     5 |    0.75000 |             0.75000 |
	|         7 | 17:46:13.0 |       1.000 |              10000000 |                     4 |    0.55000 |             0.55000 |
	|         8 | 17:46:14.7 |       1.000 |              10000000 |                     5 |    0.35000 |             0.35000 |
	|         9 | 17:46:16.3 |       1.000 |              10000000 |                     6 |    0.15000 |             0.15000 |
	|        10 | 17:46:18.2 |       1.000 |              10000000 |                     5 |    0.70000 |             0.70000 |
	|        11 | 17:46:19.9 |       1.000 |              10000000 |                     4 |    0.50000 |             0.50000 |
	|        12 | 17:46:21.6 |       1.000 |              10000000 |                     3 |    0.30000 |             0.30000 |
	|        13 | 17:46:23.2 |       1.000 |              10000000 |                     5 |    0.10000 |             0.10000 |
	|        14 | 17:46:25.1 |       1.000 |              10000000 |                     4 |    0.65000 |             0.65000 |
	|        15 | 17:46:26.8 |       1.000 |              10000000 |                     5 |    0.45000 |             0.45000 |
	|        16 | 17:46:28.4 |       1.000 |              10000000 |                     5 |    0.25000 |             0.25000 |
	|        17 | 17:46:30.0 |       1.000 |              10000000 |                     4 |    0.05000 |             0.05000 |
	+-----------+------------+-------------+-----------------------+-----------------------+------------+---------------------+
	generator interlace_tomo_scan ['23914c'] (scan num: 77)
	wrote: /home/prjemian/Documents/eclipse/use_bluesky/plans/developer_77.h5

**Comment by prjemian** [comment]
## ophyd
*  area detector config: http://nsls-ii.github.io/ophyd/area-detector.html
* sim detector: http://nsls-ii.github.io/ophyd/area-detector.html#simulated
* motor check limits: http://nsls-ii.github.io/ophyd/builtin-devices.html#ophyd.epics_motor.EpicsMotor.check_value

**Comment by prjemian** [comment]
ready for beam line implementation

**Comment by danielballan** [comment]
:clap:

**Comment by prjemian** [comment]
for those following at some distance, moving now to next milestone: [Initial tests at (APS station) 32-ID-C](https://github.com/BCDA-APS/use_bluesky/milestones)
